[package]
name = "cartridge-switcher"
version.workspace = true
edition.workspace = true

[dependencies]
cartridge-common = { path = "../common", default-features = false }

# Override linker script
[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tswitcher/linker.ld"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
