[package]
name = "cartridge-packager"
version.workspace = true
edition.workspace = true

[dependencies]
cartridge-common = { path = "../../common", features = ["std", "serde"] }
sha2.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }
